environment: development
port: 3033

grpc:
  port: 50051

jwt:
  access-secret: your-access-secret-key
  refresh-secret: your-refresh-secret-key
  access-expiry: 3600  # 1 hour in seconds
  refresh-expiry: 2592000  # 30 days in seconds

ratelimiter:
  burst: 10
  rate: 2

codec:
  secret-key: 1234567890  # Change this to a secure key

casbin:
  dsn: mysql://user:password@mysql:3306/casbin

database:
  mysql:
    host: mysql
    port: 3306  # Updated to match docker-compose
    user: user  # Changed to match docker-compose
    password: password  # Changed to match docker-compose
    database: book_system

redis:
  host: redis
  port: 6379  # Updated to match docker-compose
  user: ""  # Redis doesn't use username by default
  password: ""  # No password set in docker-compose
  database: "0"  # Default Redis database

minio:
  host: minio
  port: 9000  # Updated to match docker-compose
  access-key: minioadmin  # Matches docker-compose
  secret-key: minioadmin  # Matches docker-compose
  location: us-east-1
  default-bucket: book-system
  secure: false
  return-url: http://localhost:8080
